### ISSUE TITLE
The detail table rows are misaligned

### ISSUE THREAD

**Issue by MichalBryxi** [winds-mobi/winds-mobi-client-js#9]
## How to reproduce
1. GOTO: https://winds.mobi/stations/map/holfuy-1804
2. In the "Wind last hour" and "Air" rows see that every 2nd+ row is misaligned (see screenshot for colour matching the row data)

## Expected behaviour
- The label on the left and the data on the right align correctly to each other and sit on one row

## Screenshots
![Screenshot 2024-07-05 at 07 15 43](https://github.com/winds-mobi/winds-mobi-client-js/assets/847473/77d6076f-d727-4778-b9cf-f32cd5348214)

**Comment by MichalBryxi** [comment]
Note: This seems avoidable by using `<table>` instead of set of `<div>`s?

**Comment by ysavary** [comment]
Yeah, it was difficult to align everything in all the cases!

I updated the readme of this repository:

> This is the current [winds.mobi](https://winds.mobi/) web client but this project uses deprecated frameworks and tools like [AngularJS](https://angularjs.org/) and is no more actively maintained. If you would like to share your own version that will eventually replace this client, please open an issue that presents your project.

But please be welcome to open PRs that address the issues you found.

**Comment by MichalBryxi** [comment]
Thanks. Will try to spawn PRs to fix the "easy to fix" bugs.

Might try to tinker with own client.

But just to be sure: 
1) What runs on winds.mobi the website is the contents of this repo?
2) This repo is effectively the only client? I have not seen Android app. I'm not aware of any other UI for the users?

**Comment by ysavary** [comment]
> 1. What runs on winds.mobi the website is the contents of this repo?

Yes, it's literally a `git checkout master` directory served by [Caddy](https://github.com/caddyserver/caddy) with this [configuration](https://github.com/winds-mobi/winds-mobi-client-js/blob/dc78ca0b8d6a0c51b1c0c8a81bd29c690ea943e0/deploy/Caddyfile#L13)

> 2. This repo is effectively the only client? I have not seen Android app. I'm not aware of any other UI for the users?

There was an Android and an iOS native application many years ago but I removed them from the store. I replaced them by this "pwa" application. @s-reynier is the owner of the [Garmin client](https://github.com/winds-mobi/winds-mobi-client-garmin) and he is managing the deployment to the [Garmin Connect IQ Store](https://apps.garmin.com/fr-FR/apps/2cbd572e-04f5-4edd-b2ce-595e74b64e33)

**Comment by MichalBryxi** [comment]
Ok so just to document this: Since my environment is a bit different I tried to use [volta](https://docs.volta.sh/guide/getting-started) to install required node version (v4.2.2) and I needed to add following to `package.json`:

```
  "scripts": {
    "gulp": "gulp",
  },
```

To be able then to run `npm run gulp`, which unfortunately ends on:

```
npm run gulp

> windmobile@2.0.0 gulp /Users/michal/vast.ch/winds-mobi-client-js
> gulp

[21:03:10] Using gulpfile ~/vast.ch/winds-mobi-client-js/gulpfile.js
[21:03:10] Starting 'js'...
[21:03:10] Starting 'sass'...
[21:03:10] Finished 'sass' after 5.16 ms
[21:03:10] Starting 'html'...
[21:03:10] Finished 'html' after 1.08 ms
/Users/michal/vast.ch/winds-mobi-client-js/node_modules/browserify/node_modules/insert-module-globals/node_modules/combine-source-map/node_modules/inline-source-map/index.js:97
    return Buffer.from(map).toString('base64');
                  ^

TypeError: this is not a typed array.
    at Function.from (native)
    at Generator.base64Encode (/Users/michal/vast.ch/winds-mobi-client-js/node_modules/browserify/node_modules/insert-module-globals/node_modules/combine-source-map/node_modules/inline-source-map/index.js:97:19)
    at Generator.inlineMappingUrl (/Users/michal/vast.ch/winds-mobi-client-js/node_modules/browserify/node_modules/insert-module-globals/node_modules/combine-source-map/node_modules/inline-source-map/index.js:109:94)
    at Combiner.comment (/Users/michal/vast.ch/winds-mobi-client-js/node_modules/browserify/node_modules/insert-module-globals/node_modules/combine-source-map/index.js:134:25)
    at closeOver (/Users/michal/vast.ch/winds-mobi-client-js/node_modules/browserify/node_modules/insert-module-globals/index.js:190:21)
    at DestroyableTransform.end [as _flush] (/Users/michal/vast.ch/winds-mobi-client-js/node_modules/browserify/node_modules/insert-module-globals/index.js:145:19)
    at DestroyableTransform.prefinish (/Users/michal/vast.ch/winds-mobi-client-js/node_modules/browserify/node_modules/readable-stream/lib/_stream_transform.js:138:10)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
    at prefinish (/Users/michal/vast.ch/winds-mobi-client-js/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:619:14)
```

Environment:

```
npm --version
2.14.7

node --version
v4.2.2
```

After some monkey-patching I got further, but there are more and more things to resolve. So either I'm doing something silly or the build is not really stable.

Either way this cosmetic issue does not seem to be worth the investment and we might try to see if we want to try to build new UI interface for winds.mobi.

**Comment by ysavary** [comment]
Thank you for trying 👍

I managed to build it from scratch by using docker, after fixing a possible wrong import in scss file. I still have to test that removing this import has no effect:

```
git clone -b bugfix/remove-mapbox-scss-import https://github.com/winds-mobi/winds-mobi-client-js.git
cd winds-mobi-client-js
docker run --platform=linux/amd64 --volume=./:/app node:4 npm --prefix=/app install
docker run --platform=linux/amd64 --volume=./:/app node:4 npm --prefix=/app run gulp --production
```

```
> windmobile@2.0.0 gulp /app
> gulp
[15:45:04] Using gulpfile /app/gulpfile.js
[15:45:04] Starting 'js'...
[15:45:04] Starting 'sass'...
[15:45:04] Finished 'sass' after 52 ms
[15:45:04] Starting 'html'...
[15:45:04] Finished 'html' after 16 ms
[15:45:08] Finished 'js' after 3.84 s
[15:45:08] Starting 'default'...
[15:45:08] Finished 'default' after 81 μs
```

**Comment by MichalBryxi** [comment]
Perfection:

![Screenshot 2024-08-01 at 11 57 56](https://github.com/user-attachments/assets/d87242e1-d8c0-4f40-b52f-34ff220e55df)
